name: Checkout and Deploy Functions Project to Firebase
on:
  push:
    branches: main

jobs:
  build:
    name: Build and Deploy to Production
    runs-on: ubuntu-latest

    env:
      working-directory: ./functions

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm install
        working-directory: ${{ env.working-directory }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
